name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/nuage
          URL="http://16.171.174.229/:5000"
          HTTP_STATUS=$(curl -s --connect-timeout 5 "$URL")
          echo "HTTP Status: $HTTP_STATUS"
          echo "Response content:"
          cat test.txt

