name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          PATH_TO_CHECK="/home/ubuntu/nuage"
          if [ -e "$PATH_TO_CHECK" ]; then
            cd /home/ubuntu/nuage
            chmod +x deployment.sh
            ./deployment.sh
          else
            cd /home/ubuntu
            git clone https://github.com/hgulati123/nuage.git
            python3 -m venv venv
            source venv/bin/activate
            cd /home/ubuntu/nuage
            chmod +x deployment.sh
            ./deployment.sh
          fi

