name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/nuage
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          PID=$(pgrep -f "python3 app.py")
          curl -s http://172.31.38.67:5000 > test.txt
          if [ -s test.txt ]; then
            echo "Stopping existing Flask process..."
            kill -9 "$PID"
            sleep 10
            nohup python3 app.py > output.log 2>&1 &
          else
            nohup python3 app.py > output.log 2>&1 &
          fi
